name: onejoker
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/lcrocker/ojpoker

environment:
  sdk: ^3.5.3

dependencies:
  msgpack_dart: ^1.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
