[package]
name = "onejoker"
version = "0.1.0"
authors = ["Lee Daniel Crocker <lee@onejoker.com>"]
edition = "2021"

[profile.release]
codegen-units = 1
debug = 1
lto = "fat"
panic = "abort"

[profile.dev]
strip = false
panic = "unwind"
split-debuginfo = "unpacked"

[build]
rustflags = [ "-Clink-arg=-fuse-ld=lld", "-Ctarget-cpu=native" ]

[dependencies]
anyhow = "1.0.71"
serde = { version = "1.0.210", features = [ "derive" ] }
rmp-serde = "1.3.0"

[[bin]]
name = "bth"
path = "src/bin/bth.rs"
doc = false
