[package]
name = "onejoker"
version = "0.1.0"
authors = ["Lee Daniel Crocker <lee@onejoker.com>"]
edition = "2021"

[profile.release]
strip = true
lto = true
panic = "abort"

[dependencies]
anyhow = "1.0.71"
serde = { version = "1.0.210", features = [ "derive" ] }
rmp-serde = "1.3.0"

[[bin]]
name = "bth"
path = "src/bin/bth.rs"
doc = false
