[package]
name = "onejoker"
version = "0.1.0"
authors = ["Lee Daniel Crocker <lee@onejoker.com>"]
edition = "2021"

[profile.release]
codegen-units = 1
debug = 1
lto = "fat"
panic = "abort"

[profile.dev]
strip = false
panic = "unwind"
split-debuginfo = "unpacked"

[build]
rustflags = [ "-Clink-arg=-fuse-ld=lld", "-Ctarget-cpu=native" ]

[dependencies]
json5 = "0.4.1"
serde = { version = "1.0.214", features = ["derive"] }

[[bin]]
name = "bth"
path = "src/bin/bth.rs"
doc = false

[[bin]]
name = "primes"
path = "src/bin/primes.rs"
doc = false

